name: RK2
run-name: Doing work
on: [push]
jobs:
  compile_on_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: checkout and get modules
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build for tests
        run: |
          cmake -H. -B_build -DBUILD_TESTS=ON
          cmake --build _build
      - name: Run tests
        run: |
          cmake --build _build --target test -- ARGS=--verbose
      - name: Build for main.cpp
        run: |
          cmake -H. -B_build -DBUILD_MAIN=ON
          cmake --build _build
      - name: Test if main.cpp actually present
        run: ./_build/main
      - name: Make artifact from compiled main
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: _build/main